AWSTemplateFormatVersion: 2010-09-09
Description: Bucket for Apollo GraphQL Lambda code

Resources:
  LambdaCodeBucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: Private

Outputs:
  LambdaBucket:
    Description: Bucket for Lambda code
    Value:
      Ref: LambdaCodeBucket